# .github/workflows/ci.yml

name: CI/CD Pipeline for ML Model Training

# Wykonuj akcje przy każdym pushu do gałęzi main
on:
  push:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Clone external repository
        run: |
          git clone https://Bambi54:${{ secrets.LAB2_REPO_KEY }}@github.com/PJATK-ASI-2024/Lab2---Obr-bka-danych.git external-repo
        env:
          token: ${{ secrets.LAB2_REPO_KEY }}

      - name: Install external project dependencies
        run: |
          python -m pip install --upgrade pip
          cd external-repo
          pip install -r requirements.txt

      - name: Run script from external repository
        run: |
          cd external-repo
          python generator_danych.py -s 253347
      
      - name: Install project dependencies
        run: |
          pip install -r requirements.txt

      - name: Fetch data from Google Sheet
        env:
          GOOGLE_SHEETS_API_KEY_JSON: ${{ secrets.GOOGLE_SHEETS_API_KEY_JSON }}
        run: |
          echo "$GOOGLE_SHEETS_API_KEY_JSON" > credentials.json
          python s25347.py
